apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: default
data:
  APP_PORT: "8080"
  APP_ENV: "production"
  DB_HOST: "user-service-mysql"
  DB_PORT: "3306"
  DB_DATABASE: "user_service"
  DB_USERNAME: "root"
  KAFKA_BROKER: "kafka.default.svc.cluster.local:9092"
